### ISSUE TITLE
Program hangs if there is no icon file

### ISSUE THREAD

**Issue by SacredSkull** [Jeflux/ckLua#1]
When I tried your binary build (haven't built it myself, yet) I found that it hung immediately. I started debugging it and found it was returning a FileNotFound exception. It was looking specifically for `%USER%/icon.ico` (in my case C:/Users/Peter/icon.ico).

The program started working fine after I copied one with that path/name.

**Comment by SacredSkull** [comment]
Additionally, it seems it looks only in the User directory, the program directory doesn't work

**Comment by SacredSkull** [comment]
(Unrelated)

When installing libusb, there are several interfaces available. Do I need to replace the driver for each interface, or is it a specific one? I know that the ColourSpectrum program mentioned replacing the 3rd end-point (which could be either interface 2 or 3, as it is zero-indexed)

**Comment by Jeflux** [comment]
Thanks for the heads up! I will check it out as soon as possible

**Comment by Jeflux** [comment]
This issue should now be fixed
